#!/bin/bash
# detect-devices.sh - Raspberry Pi Camera Device Detection Helper
# Helps identify which devices exist on your system for docker-compose.yaml configuration

set -e

# Arrays to store detected devices
CORE_DEVICES=()
MEDIA_DEVICES=()
VIDEO_DEVICES=()

echo "[INFO] motion-in-ocean - Camera Device Detection"
echo "=========================================="
echo ""

# Check if running on Raspberry Pi
if [ ! -f /proc/device-tree/model ]; then
    echo "[WARN] Not running on Raspberry Pi hardware"
    echo "This script is designed for Raspberry Pi systems."
    echo ""
fi

# Check for required core devices
echo "[INFO] Core devices (required):"
echo ""

check_device() {
    local device_path=$1
    local description=$2
    if [ -e "$device_path" ]; then
        echo "  [INFO] $device_path - $description"
        stat -c "    Permissions: %A Owner: %U:%G" "$device_path"
        CORE_DEVICES+=("$device_path")
        return 0
    else
        echo "  [WARN] $device_path - $description (NOT FOUND)"
        return 1
    fi
}

# Core devices - DMA heap (map individual device nodes, not directory)
if [ -d "/dev/dma_heap" ]; then
    echo "  [INFO] /dev/dma_heap - Memory management for libcamera (directory)"
    for file in /dev/dma_heap/*; do
        if [ -e "$file" ]; then
            stat -c "    %A %U:%G %n" "$file"
            CORE_DEVICES+=("$file")
        fi
    done
else
    echo "  [WARN] /dev/dma_heap - Memory management for libcamera (NOT FOUND)"
fi
check_device "/dev/vchiq" "VideoCore Host Interface"

echo ""
echo "[INFO] Media controller devices (required for libcamera):"
echo ""

# Use a glob to find media devices
for device in /dev/media*; do
    if [ -e "$device" ]; then
        echo "  [INFO] $device"
        stat -c "    Permissions: %A Owner: %U:%G" "$device"
        MEDIA_DEVICES+=("$device")
    fi
done

if [ ${#MEDIA_DEVICES[@]} -eq 0 ]; then
    echo "  [WARN] No /dev/media* devices found"
    echo ""
    echo "  Troubleshooting:"
    echo "  1. Ensure camera is enabled: sudo raspi-config"
    echo "  2. Check if camera driver is loaded: lsmod | grep bcm2835"
    echo "  3. Reboot after enabling camera"
fi

echo ""
echo "[INFO] Video devices (camera nodes):"
echo ""

# Use a glob to find video devices
for device in /dev/video*; do
    if [ -e "$device" ]; then
        echo "  [INFO] $device"
        stat -c "    Permissions: %A Owner: %U:%G" "$device"
        VIDEO_DEVICES+=("$device")
    fi
done

if [ ${#VIDEO_DEVICES[@]} -eq 0 ]; then
    echo "  [WARN] No /dev/video* devices found"
    echo ""
    echo "  Troubleshooting:"
    echo "  1. Ensure camera is enabled: sudo raspi-config"
    echo "  2. Check camera connection and reboot"
    echo "  3. Test with: rpicam-hello --list-cameras"
fi

echo ""
echo "[INFO] Recommended docker-compose.yaml configuration:"
echo ""
echo "devices:"
for device in "${CORE_DEVICES[@]}"; do
    echo "  - $device:$device"
done
for device in "${MEDIA_DEVICES[@]}"; do
    echo "  - $device:$device"
done
for device in "${VIDEO_DEVICES[@]}"; do
    echo "  - $device:$device"
done

echo ""
echo "[INFO] Alternative: use device_cgroup_rules (automatically allows all matching devices):"
echo ""
echo "device_cgroup_rules:"
echo "  - 'c 253:* rmw'  # /dev/dma_heap/* (char device 253)"
echo "  - 'c 511:* rmw'  # /dev/vchiq"
echo "  - 'c 81:* rmw'   # /dev/video*"
echo "  - 'c 250:* rmw'  # /dev/media* (media controllers)"
echo ""

# Check camera functionality
echo "[INFO] Camera test:"
echo ""
if command -v rpicam-hello &> /dev/null; then
    echo "Testing camera with rpicam-hello..."
    if timeout 3 rpicam-hello --list-cameras 2>/dev/null; then
        echo "  [INFO] Camera detected and working."
    else
        echo "  [ERROR] Camera test failed - check camera connection"
    fi
else
    echo "  [WARN] rpicam-hello not found (install with: sudo apt install libcamera-apps)"
fi

echo "Do you want to create a docker-compose.override.yaml file with the detected devices? (y/N):"
read -r CREATE_OVERRIDE

if [[ "${CREATE_OVERRIDE}" =~ ^[Yy]$ ]]; then
    cat << EOF > docker-compose.override.yaml
# Docker Compose override file - generated by detect-devices.sh

services:
  motion-in-ocean:
    devices:
EOF
    for device in "${CORE_DEVICES[@]}"; do
        echo "      - $device:$device" >> docker-compose.override.yaml
    done
    for device in "${MEDIA_DEVICES[@]}"; do
        echo "      - $device:$device" >> docker-compose.override.yaml
    done
    for device in "${VIDEO_DEVICES[@]}"; do
        echo "      - $device:$device" >> docker-compose.override.yaml
    done
    cat << EOF >> docker-compose.override.yaml
    privileged: true # Required for full device access
EOF
    echo "[INFO] Created docker-compose.override.yaml with detected devices."
else
    echo "Skipping creation of docker-compose.override.yaml."
fi

echo ""
echo "[INFO] Detection complete."
echo ""
echo "Next steps:"
echo "1. (Optional) Run ./setup.sh for guided setup (copies .env and prints the docker compose command)."
echo "2. Update docker-compose.yaml with the devices shown above."
echo "3. Or use device_cgroup_rules for automatic device access."
if [ -f docker-compose.override.yaml ]; then
    echo "4. Run: docker compose -f docker-compose.yaml -f docker-compose.override.yaml up -d"
else
    echo "4. Run: docker compose up -d"
fi
echo ""
