name: Feature Request
description: Suggest an idea or improvement for motion-in-ocean
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement 🌊📷

        motion-in-ocean is intentionally lightweight and homelab-focused:
        - Raspberry Pi CSI camera streaming inside Docker
        - Picamera2/libcamera stack
        - Simple deployment via GHCR + docker-compose

        Great feature requests are:
        - practical homelab improvements
        - low complexity
        - optional via env flags
        - minimal new dependencies

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: "I want to consume the stream in Home Assistant, but setup requires manual configuration..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see added/changed?
      placeholder: "Add a /metrics endpoint for Prometheus; add a docs example for HA camera integration..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What have you tried or considered already?
      placeholder: "Using a reverse proxy + auth; using MJPEG streamer; using motion..."
    validations:
      required: false

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How valuable is this feature?
      options:
        - Nice to have
        - Useful for many users
        - Important for typical homelab deployments
        - Critical / blocker
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope / notes
      description: Include any details about how it should work (env flags, defaults, behaviour).
      placeholder: |
        - Should be optional: ENABLE_METRICS=true
        - Default disabled
        - No heavy dependencies
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I’d be willing to implement this feature and open a PR
          required: false
        - label: I can help test this feature on Raspberry Pi hardware
          required: false
        - label: I can contribute docs/examples for this feature
          required: false
