"""Type stubs for picamera2 - Raspberry Pi camera library."""

from typing import Any, Optional

class Picamera2:
    """Picamera2 Camera control class."""
    
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def create_preview_configuration(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def create_still_configuration(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def configure(self, config: dict[str, Any], *args: Any, **kwargs: Any) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def start_recording(self, *args: Any, **kwargs: Any) -> None: ...
    def capture_file(self, *args: Any, **kwargs: Any) -> None: ...
    def capture_metadata(self) -> dict[str, Any]: ...
    def close(self) -> None: ...

class Encoder:
    """Base encoder class."""
    pass

class Output:
    """Base output class."""
    pass
